# Generated by Django 4.1.1 on 2023-04-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_watchlist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField()),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.watchlist')),
            ],
            options={
                'db_table': 'ticket_sales',
            },
        ),
    ]
